"""GAIA evaluation — KIMI × C2.

Generated by scripts/gen_eval_configs.py. Do not edit by hand — regenerate
instead. Inherits from ./config_gaia_c2.py and overrides every model_id to point
at the chosen model.

Model: or-kimi-k2.5
Kimi K2.5 via OpenRouter (operator preference — OPENROUTER_API_KEY). Native MOONSHOT_API_KEY path is intentionally left as a placeholder. OpenRouter does not enforce Moonshot's thinking-on default, so this also satisfies the C2/C3 JSON-output requirement without an extra_body override.

Output dir: workdir/gaia_c2_kimi_<run_id>/

Initial-run knobs (override via --cfg-options):
  - max_samples=N        # cap to first N questions; leave None for full set
  - concurrency=K        # parallel questions per config (default 4)
  - dataset.split="validation"  # smoke-test against the labeled validation
                                # split before submitting on test
"""

_base_ = './config_gaia_c2.py'

import os as _os
from datetime import datetime as _datetime
_RUN_ID = _os.environ.get("DRA_RUN_ID") or _datetime.now().strftime("%Y%m%d_%H%M%S")
del _os, _datetime

tag = f"gaia_c2_kimi_{_RUN_ID}"

# ---- model overrides --------------------------------------------------------

# All four agents use the SAME model_id under the single-model evaluation
# constraint. C2/C3 reviewer + skill extractor inherit this id via the planner.

deep_researcher_agent_config = dict(
    type="deep_researcher_agent",
    name="deep_researcher_agent",
    model_id='or-kimi-k2.5',
    description="A deep researcher agent that can conduct extensive web searches.",
    max_steps=3,
    template_path="src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml",
    provide_run_summary=True,
    tools=["deep_researcher_tool", "python_interpreter_tool"],
)

deep_analyzer_agent_config = dict(
    type="deep_analyzer_agent",
    name="deep_analyzer_agent",
    model_id='or-kimi-k2.5',
    description="A deep analyzer agent that can perform systematic, step-by-step analysis.",
    max_steps=3,
    template_path="src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml",
    provide_run_summary=True,
    tools=["deep_analyzer_tool", "python_interpreter_tool"],
)

browser_use_agent_config = dict(
    type="browser_use_agent",
    name="browser_use_agent",
    model_id='or-kimi-k2.5',
    description="A browser use agent that can search relevant web pages and interact with them.",
    max_steps=5,
    template_path="src/agent/browser_use_agent/prompts/browser_use_agent.yaml",
    provide_run_summary=True,
    tools=["auto_browser_use_tool", "python_interpreter_tool"],
)

planning_agent_config = dict(
    type="adaptive_planning_agent",
    name="adaptive_planning_agent",
    model_id='or-kimi-k2.5',
    description=(
        "An adaptive planning agent with reactive diagnose/modify tools "
        "plus a structural REVIEW step (condition C2)."
    ),
    max_steps=25,
    template_path="src/agent/adaptive_planning_agent/prompts/adaptive_planning_agent_c2.yaml",
    provide_run_summary=True,
    tools=["planning_tool"],
    managed_agents=["deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent"],
    enable_review=True,
)
agent_config = planning_agent_config

# ---- tool overrides ---------------------------------------------------------

deep_researcher_tool_config = dict(
    type="deep_researcher_tool",
    model_id='or-kimi-k2.5',
    max_depth=2,
    max_insights=20,
    time_limit_seconds=60,
    max_follow_ups=3,
)

deep_analyzer_tool_config = dict(
    type="deep_analyzer_tool",
    analyzer_model_ids=['or-kimi-k2.5'],
    summarizer_model_id='or-kimi-k2.5',
)

# auto_browser_use_tool requires a LangChain ChatModel wrapper, registered
# alongside each native model in src/models/models.py.
#
# max_steps=15 is the S4-time browser step cap (down from the
# AutoBrowserUseTool class default of 50). Rationale: typical GAIA browser
# flows need 2-12 internal steps; beyond ~15 the marginal accuracy gain is
# dominated by stuck-loop waste (CAPTCHA retries, cookie-modal fights,
# infinite scrolls). A single stuck 50-step invocation burns ~$0.10-1.00
# and 8-12 min wall. Applied uniformly across all 16 cells so
# C0/C1/C2/C3 deltas aren't contaminated by per-condition browser budget
# differences. For local smoke tests, override via --cfg-options
# (auto_browser_use_tool_config.max_steps=8). See
# docs/handoffs/HANDOFF_TEST_EVAL.md "Browser step cap policy".
auto_browser_use_tool_config = dict(
    type="auto_browser_use_tool",
    model_id='langchain-or-kimi-k2.5',
    max_steps=15,
)

# ---- run knobs --------------------------------------------------------------

# Default: full GAIA test split. Override on the CLI for smoke tests:
#   python examples/run_gaia.py --config configs/config_gaia_c2_kimi.py \
#     --cfg-options max_samples=10 dataset.split=validation
max_samples = None
concurrency = 4

# Per-question wall clock timeout (secs). Pinned 2026-04-20 after the
# E0 v3 resume surfaced an asymmetry: training had been running at 1800s
# but test-time configs silently fell back to the run_gaia.py default of
# 1200s, biasing the C0-C2 vs C3 ablation at test time. Now uniformly
# 1800s across training (E0) and test (E3) for every (model, condition).
per_question_timeout_secs = 1800
