"""GAIA evaluation — MISTRAL × C0.

Generated by scripts/gen_eval_configs.py. Do not edit by hand — regenerate
instead. Inherits from ./config_gaia_c0.py and overrides every model_id to point
at the chosen model.

Model: mistral-small
Mistral Small 4 (mistral-small-2603) — native multimodal, no thinking mode.

Output dir: workdir/gaia_c0_mistral_<run_id>/

Initial-run knobs (override via --cfg-options):
  - max_samples=N        # cap to first N questions; leave None for full set
  - concurrency=K        # parallel questions per config (default 4)
  - dataset.split="validation"  # smoke-test against the labeled validation
                                # split before submitting on test
"""

_base_ = './config_gaia_c0.py'

import os as _os
from datetime import datetime as _datetime
_RUN_ID = _os.environ.get("DRA_RUN_ID") or _datetime.now().strftime("%Y%m%d_%H%M%S")
del _os, _datetime

tag = f"gaia_c0_mistral_{_RUN_ID}"

# ---- model overrides --------------------------------------------------------

# All four agents use the SAME model_id under the single-model evaluation
# constraint. C3/C4 reviewer + skill extractor inherit this id via the planner.

deep_researcher_agent_config = dict(
    type="deep_researcher_agent",
    name="deep_researcher_agent",
    model_id='mistral-small',
    description="A deep researcher agent that can conduct extensive web searches.",
    max_steps=3,
    template_path="src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml",
    provide_run_summary=True,
    tools=["deep_researcher_tool", "python_interpreter_tool"],
)

deep_analyzer_agent_config = dict(
    type="deep_analyzer_agent",
    name="deep_analyzer_agent",
    model_id='mistral-small',
    description="A deep analyzer agent that can perform systematic, step-by-step analysis.",
    max_steps=3,
    template_path="src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml",
    provide_run_summary=True,
    tools=["deep_analyzer_tool", "python_interpreter_tool"],
)

browser_use_agent_config = dict(
    type="browser_use_agent",
    name="browser_use_agent",
    model_id='mistral-small',
    description="A browser use agent that can search relevant web pages and interact with them.",
    max_steps=5,
    template_path="src/agent/browser_use_agent/prompts/browser_use_agent.yaml",
    provide_run_summary=True,
    tools=["auto_browser_use_tool", "python_interpreter_tool"],
)

planning_agent_config = dict(
    type="planning_agent",
    name="planning_agent",
    model_id='mistral-small',
    description="A planning agent that can plan the steps to complete the task.",
    max_steps=20,
    template_path="src/agent/planning_agent/prompts/planning_agent.yaml",
    provide_run_summary=True,
    tools=["planning_tool"],
    managed_agents=["deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent"],
)
agent_config = planning_agent_config

# ---- tool overrides ---------------------------------------------------------

deep_researcher_tool_config = dict(
    type="deep_researcher_tool",
    model_id='mistral-small',
    max_depth=2,
    max_insights=20,
    time_limit_seconds=60,
    max_follow_ups=3,
)

deep_analyzer_tool_config = dict(
    type="deep_analyzer_tool",
    analyzer_model_ids=['mistral-small'],
    summarizer_model_id='mistral-small',
)

# auto_browser_use_tool requires a LangChain ChatModel wrapper, registered
# alongside each native model in src/models/models.py.
#
# max_steps=15 is the S4-time browser step cap (down from the
# AutoBrowserUseTool class default of 50). Rationale: typical GAIA browser
# flows need 2-12 internal steps; beyond ~15 the marginal accuracy gain is
# dominated by stuck-loop waste (CAPTCHA retries, cookie-modal fights,
# infinite scrolls). A single stuck 50-step invocation burns ~$0.10-1.00
# and 8-12 min wall. Applied uniformly across all 16 cells so
# C0/C2/C3/C4 deltas aren't contaminated by per-condition browser budget
# differences. For local smoke tests, override via --cfg-options
# (auto_browser_use_tool_config.max_steps=8). See
# docs/handoffs/HANDOFF_TEST_EVAL.md "Browser step cap policy".
auto_browser_use_tool_config = dict(
    type="auto_browser_use_tool",
    model_id='langchain-mistral-small',
    max_steps=15,
)

# ---- run knobs --------------------------------------------------------------

# Default: full GAIA test split. Override on the CLI for smoke tests:
#   python examples/run_gaia.py --config configs/config_gaia_c0_mistral.py \
#     --cfg-options max_samples=10 dataset.split=validation
max_samples = None
concurrency = 4

# Per-question wall clock timeout (secs). Pinned 2026-04-20 for fairness
# with E0 v3 C4 training (which used 1800s). Previously inherited
# run_gaia.py default 1200, creating a training/test asymmetry that
# could bias the C0-C3 vs C4 ablation at test time.
per_question_timeout_secs = 1800
