"""GAIA evaluation — GEMMA × C3.

Generated by scripts/gen_eval_configs.py. Do not edit by hand — regenerate
instead. Inherits from ./config_gaia_c3.py and overrides every model_id to point
at the chosen model.

Model: or-gemma-4-31b-it
Gemma 4 31B Instruct via OpenRouter (D4, 2026-04-18). Dense Google frontier slot alongside the MoE variants (Mistral, Kimi, Qwen). Text+image+video modalities (no audio). Apache 2.0. Provider pin to DeepInfra+Together (both vLLM-backed, latest gemma4 parser) is set at registration in `src/models/models.py`; reasoning mode disabled there to prevent thinking-channel contamination of tool output. Live smoke probe 2026-04-18 confirmed `tool_choice="required"` works directly with this provider pin (finish_reason="tool_calls", no special-token leaks), so Gemma is NOT in `MODELS_REJECTING_REQUIRED` — the dispatcher passes `"required"` through unchanged. Concurrency is capped at 4 in `scripts/run_eval_matrix.sh` for this stream only (vLLM #39392 pad-bug under parallel load). $0.13 in / $0.38 out per M tokens.

Output dir: workdir/gaia_c3_gemma_<run_id>/

Initial-run knobs (override via --cfg-options):
  - max_samples=N        # cap to first N questions; leave None for full set
  - concurrency=K        # parallel questions per config (default 4)
  - dataset.split="validation"  # smoke-test against the labeled validation
                                # split before submitting on test
"""

_base_ = './config_gaia_c3.py'

import os as _os
from datetime import datetime as _datetime
_RUN_ID = _os.environ.get("DRA_RUN_ID") or _datetime.now().strftime("%Y%m%d_%H%M%S")
del _os, _datetime

tag = f"gaia_c3_gemma_{_RUN_ID}"

# ---- model overrides --------------------------------------------------------

# All four agents use the SAME model_id under the single-model evaluation
# constraint. C2/C3 reviewer + skill extractor inherit this id via the planner.

deep_researcher_agent_config = dict(
    type="deep_researcher_agent",
    name="deep_researcher_agent",
    model_id='or-gemma-4-31b-it',
    description="A deep researcher agent that can conduct extensive web searches.",
    max_steps=3,
    template_path="src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml",
    provide_run_summary=True,
    tools=["deep_researcher_tool", "python_interpreter_tool"],
)

deep_analyzer_agent_config = dict(
    type="deep_analyzer_agent",
    name="deep_analyzer_agent",
    model_id='or-gemma-4-31b-it',
    description="A deep analyzer agent that can perform systematic, step-by-step analysis.",
    max_steps=3,
    template_path="src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml",
    provide_run_summary=True,
    tools=["deep_analyzer_tool", "python_interpreter_tool"],
)

browser_use_agent_config = dict(
    type="browser_use_agent",
    name="browser_use_agent",
    model_id='or-gemma-4-31b-it',
    description="A browser use agent that can search relevant web pages and interact with them.",
    max_steps=5,
    template_path="src/agent/browser_use_agent/prompts/browser_use_agent.yaml",
    provide_run_summary=True,
    tools=["auto_browser_use_tool", "python_interpreter_tool"],
)

planning_agent_config = dict(
    type="adaptive_planning_agent",
    name="adaptive_planning_agent",
    model_id='or-gemma-4-31b-it',
    description=(
        "An adaptive planning agent with reactive diagnose/modify tools, a "
        "structural REVIEW step, and a cross-task skill library (C3)."
    ),
    max_steps=25,
    template_path="src/agent/adaptive_planning_agent/prompts/adaptive_planning_agent_c3.yaml",
    provide_run_summary=True,
    tools=["planning_tool"],
    managed_agents=["deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent"],
    enable_review=True,
    enable_skills=True,
    enable_skill_extraction=True,
    skills_dir=f"workdir/{tag}/skills",
)
agent_config = planning_agent_config

# ---- tool overrides ---------------------------------------------------------

deep_researcher_tool_config = dict(
    type="deep_researcher_tool",
    model_id='or-gemma-4-31b-it',
    max_depth=2,
    max_insights=20,
    time_limit_seconds=60,
    max_follow_ups=3,
)

deep_analyzer_tool_config = dict(
    type="deep_analyzer_tool",
    analyzer_model_ids=['or-gemma-4-31b-it'],
    summarizer_model_id='or-gemma-4-31b-it',
)

# auto_browser_use_tool requires a LangChain ChatModel wrapper, registered
# alongside each native model in src/models/models.py.
#
# max_steps=15 is the S4-time browser step cap (down from the
# AutoBrowserUseTool class default of 50). Rationale: typical GAIA browser
# flows need 2-12 internal steps; beyond ~15 the marginal accuracy gain is
# dominated by stuck-loop waste (CAPTCHA retries, cookie-modal fights,
# infinite scrolls). A single stuck 50-step invocation burns ~$0.10-1.00
# and 8-12 min wall. Applied uniformly across all 16 cells so
# C0/C1/C2/C3 deltas aren't contaminated by per-condition browser budget
# differences. For local smoke tests, override via --cfg-options
# (auto_browser_use_tool_config.max_steps=8). See
# docs/handoffs/HANDOFF_TEST_EVAL.md "Browser step cap policy".
auto_browser_use_tool_config = dict(
    type="auto_browser_use_tool",
    model_id='langchain-or-gemma-4-31b-it',
    max_steps=15,
)

# ---- run knobs --------------------------------------------------------------

# Default: full GAIA test split. Override on the CLI for smoke tests:
#   python examples/run_gaia.py --config configs/config_gaia_c3_gemma.py \
#     --cfg-options max_samples=10 dataset.split=validation
max_samples = None
concurrency = 4

# Per-question wall clock timeout (secs). Pinned 2026-04-20 after the
# E0 v3 resume surfaced an asymmetry: training had been running at 1800s
# but test-time configs silently fell back to the run_gaia.py default of
# 1200s, biasing the C0-C2 vs C3 ablation at test time. Now uniformly
# 1800s across training (E0) and test (E3) for every (model, condition).
per_question_timeout_secs = 1800
