"""GAIA evaluation — GEMMA × C0.

Generated by scripts/gen_eval_configs.py. Do not edit by hand — regenerate
instead. Inherits from ./config_gaia_c0.py and overrides every model_id to point
at the chosen model.

Model: or-gemma-4-31b-it
Gemma 4 31B Instruct via OpenRouter (D4, 2026-04-18). Dense Google frontier slot alongside the MoE variants (Mistral, Kimi, Qwen). Text+image+video modalities (no audio). Apache 2.0. Provider pin to DeepInfra+Together (both vLLM-backed, latest gemma4 parser) is set at registration in `src/models/models.py`; reasoning mode disabled there to prevent thinking-channel contamination of tool output. tool_choice is downgraded to `"auto"` via the D5 named entry in `src/models/tool_choice.py` pending a live smoke probe. Concurrency is capped at 4 in `scripts/run_eval_matrix.sh` for this stream only (vLLM #39392 pad-bug under parallel load). $0.13 in / $0.38 out per M tokens.

Output dir: workdir/gaia_c0_gemma_<run_id>/

Initial-run knobs (override via --cfg-options):
  - max_samples=N        # cap to first N questions; leave None for full set
  - concurrency=K        # parallel questions per config (default 4)
  - dataset.split="validation"  # smoke-test against the labeled validation
                                # split before submitting on test
"""

_base_ = './config_gaia_c0.py'

import os as _os
from datetime import datetime as _datetime
_RUN_ID = _os.environ.get("DRA_RUN_ID") or _datetime.now().strftime("%Y%m%d_%H%M%S")
del _os, _datetime

tag = f"gaia_c0_gemma_{_RUN_ID}"

# ---- model overrides --------------------------------------------------------

# All four agents use the SAME model_id under the single-model evaluation
# constraint. C3/C4 reviewer + skill extractor inherit this id via the planner.

deep_researcher_agent_config = dict(
    type="deep_researcher_agent",
    name="deep_researcher_agent",
    model_id='or-gemma-4-31b-it',
    description="A deep researcher agent that can conduct extensive web searches.",
    max_steps=3,
    template_path="src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml",
    provide_run_summary=True,
    tools=["deep_researcher_tool", "python_interpreter_tool"],
)

deep_analyzer_agent_config = dict(
    type="deep_analyzer_agent",
    name="deep_analyzer_agent",
    model_id='or-gemma-4-31b-it',
    description="A deep analyzer agent that can perform systematic, step-by-step analysis.",
    max_steps=3,
    template_path="src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml",
    provide_run_summary=True,
    tools=["deep_analyzer_tool", "python_interpreter_tool"],
)

browser_use_agent_config = dict(
    type="browser_use_agent",
    name="browser_use_agent",
    model_id='or-gemma-4-31b-it',
    description="A browser use agent that can search relevant web pages and interact with them.",
    max_steps=5,
    template_path="src/agent/browser_use_agent/prompts/browser_use_agent.yaml",
    provide_run_summary=True,
    tools=["auto_browser_use_tool", "python_interpreter_tool"],
)

planning_agent_config = dict(
    type="planning_agent",
    name="planning_agent",
    model_id='or-gemma-4-31b-it',
    description="A planning agent that can plan the steps to complete the task.",
    max_steps=20,
    template_path="src/agent/planning_agent/prompts/planning_agent.yaml",
    provide_run_summary=True,
    tools=["planning_tool"],
    managed_agents=["deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent"],
)
agent_config = planning_agent_config

# ---- tool overrides ---------------------------------------------------------

deep_researcher_tool_config = dict(
    type="deep_researcher_tool",
    model_id='or-gemma-4-31b-it',
    max_depth=2,
    max_insights=20,
    time_limit_seconds=60,
    max_follow_ups=3,
)

deep_analyzer_tool_config = dict(
    type="deep_analyzer_tool",
    analyzer_model_ids=['or-gemma-4-31b-it'],
    summarizer_model_id='or-gemma-4-31b-it',
)

# auto_browser_use_tool requires a LangChain ChatModel wrapper, registered
# alongside each native model in src/models/models.py.
auto_browser_use_tool_config = dict(
    type="auto_browser_use_tool",
    model_id='langchain-or-gemma-4-31b-it',
)

# ---- run knobs --------------------------------------------------------------

# Default: full GAIA test split. Override on the CLI for smoke tests:
#   python examples/run_gaia.py --config configs/config_gaia_c0_gemma.py \
#     --cfg-options max_samples=10 dataset.split=validation
max_samples = None
concurrency = 4
