"""GAIA evaluation — MISTRAL × C3.

Generated by scripts/gen_eval_configs.py. Do not edit by hand — regenerate
instead. Inherits from ./config_gaia_c3.py and overrides every model_id to point
at the chosen model.

Model: mistral-small
Mistral Small 4 (mistral-small-2603) — native multimodal, no thinking mode.

Output dir: workdir/gaia_c3_mistral_<run_id>/

Initial-run knobs (override via --cfg-options):
  - max_samples=N        # cap to first N questions; leave None for full set
  - concurrency=K        # parallel questions per config (default 4)
  - dataset.split="validation"  # smoke-test against the labeled validation
                                # split before submitting on test
"""

_base_ = './config_gaia_c3.py'

import os as _os
from datetime import datetime as _datetime
_RUN_ID = _os.environ.get("DRA_RUN_ID") or _datetime.now().strftime("%Y%m%d_%H%M%S")
del _os, _datetime

tag = f"gaia_c3_mistral_{_RUN_ID}"

# ---- model overrides --------------------------------------------------------

# All four agents use the SAME model_id under the single-model evaluation
# constraint. C3/C4 reviewer + skill extractor inherit this id via the planner.

deep_researcher_agent_config = dict(
    type="deep_researcher_agent",
    name="deep_researcher_agent",
    model_id='mistral-small',
    description="A deep researcher agent that can conduct extensive web searches.",
    max_steps=3,
    template_path="src/agent/deep_researcher_agent/prompts/deep_researcher_agent.yaml",
    provide_run_summary=True,
    tools=["deep_researcher_tool", "python_interpreter_tool"],
)

deep_analyzer_agent_config = dict(
    type="deep_analyzer_agent",
    name="deep_analyzer_agent",
    model_id='mistral-small',
    description="A deep analyzer agent that can perform systematic, step-by-step analysis.",
    max_steps=3,
    template_path="src/agent/deep_analyzer_agent/prompts/deep_analyzer_agent.yaml",
    provide_run_summary=True,
    tools=["deep_analyzer_tool", "python_interpreter_tool"],
)

browser_use_agent_config = dict(
    type="browser_use_agent",
    name="browser_use_agent",
    model_id='mistral-small',
    description="A browser use agent that can search relevant web pages and interact with them.",
    max_steps=5,
    template_path="src/agent/browser_use_agent/prompts/browser_use_agent.yaml",
    provide_run_summary=True,
    tools=["auto_browser_use_tool", "python_interpreter_tool"],
)

planning_agent_config = dict(
    type="adaptive_planning_agent",
    name="adaptive_planning_agent",
    model_id='mistral-small',
    description=(
        "An adaptive planning agent with reactive diagnose/modify tools "
        "plus a structural REVIEW step (condition C3)."
    ),
    max_steps=25,
    template_path="src/agent/adaptive_planning_agent/prompts/adaptive_planning_agent_c3.yaml",
    provide_run_summary=True,
    tools=["planning_tool"],
    managed_agents=["deep_analyzer_agent", "browser_use_agent", "deep_researcher_agent"],
    enable_review=True,
)
agent_config = planning_agent_config

# ---- tool overrides ---------------------------------------------------------

deep_researcher_tool_config = dict(
    type="deep_researcher_tool",
    model_id='mistral-small',
    max_depth=2,
    max_insights=20,
    time_limit_seconds=60,
    max_follow_ups=3,
)

deep_analyzer_tool_config = dict(
    type="deep_analyzer_tool",
    analyzer_model_ids=['mistral-small'],
    summarizer_model_id='mistral-small',
)

# auto_browser_use_tool requires a LangChain ChatModel wrapper, registered
# alongside each native model in src/models/models.py.
auto_browser_use_tool_config = dict(
    type="auto_browser_use_tool",
    model_id='langchain-mistral-small',
)

# ---- run knobs --------------------------------------------------------------

# Default: full GAIA test split. Override on the CLI for smoke tests:
#   python examples/run_gaia.py --config configs/config_gaia_c3_mistral.py \
#     --cfg-options max_samples=10 dataset.split=validation
max_samples = None
concurrency = 4
